# Generated by Django 3.2.1 on 2021-11-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_blog_date_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
